const data = {
  charaBase: [
    {
      unit_id: 106101,
      unit_name: "ムイミ",
      kana: "むいみ",
      prefab_id: 106101,
      move_speed: 450,
      search_area_width: 162,
      atk_type: 1,
      normal_atk_cast_time: 1.8,
      guild_id: 7,
      comment: "【物理】前衛で、伝説の剣「天楼覇断剣」を振るう少女。\\n小技を駆使する通常の戦闘スタイルから一転、ユニオン\\nバースト後は「天楼覇断剣」を携え、敵を薙ぎ払う。",
      start_time: "2020/12/31 12:00:00",
      age: "16",
      guild: "？？？",
      race: "ヒューマン",
      height: "148",
      weight: "40",
      birth_month: "8",
      birth_day: "11",
      blood_type: "O",
      favorite: "冒険、思い出話",
      voice: "潘めぐみ",
      catch_copy: "さまよえる謎の少女",
      self_text: "いいんだ、アタシは……独りでも。大丈夫だから、もう慣れたからさぁ",
      actual_name: "園上 矛依未",
    },
  ],
  charaStoryStatus: [
    {
      story_id: 1061002,
      unlock_story_name: "ムイミのエピソード第2話",
      status_type_1: 2,
      status_rate_1: 60,
      status_type_2: 0,
      status_rate_2: 0,
      status_type_3: 0,
      status_rate_3: 0,
      status_type_4: 0,
      status_rate_4: 0,
      status_type_5: 0,
      status_rate_5: 0,
      chara_id_1: 1061,
      chara_id_2: 1147,
      chara_id_3: 0,
      chara_id_4: 0,
      chara_id_5: 0,
      chara_id_6: 0,
      chara_id_7: 0,
      chara_id_8: 0,
      chara_id_9: 0,
      chara_id_10: 0,
    },
    {
      story_id: 1061003,
      unlock_story_name: "ムイミのエピソード第3話",
      status_type_1: 2,
      status_rate_1: 80,
      status_type_2: 6,
      status_rate_2: 10,
      status_type_3: 0,
      status_rate_3: 0,
      status_type_4: 0,
      status_rate_4: 0,
      status_type_5: 0,
      status_rate_5: 0,
      chara_id_1: 1061,
      chara_id_2: 1147,
      chara_id_3: 0,
      chara_id_4: 0,
      chara_id_5: 0,
      chara_id_6: 0,
      chara_id_7: 0,
      chara_id_8: 0,
      chara_id_9: 0,
      chara_id_10: 0,
    },
    {
      story_id: 1061004,
      unlock_story_name: "ムイミのエピソード第4話",
      status_type_1: 2,
      status_rate_1: 100,
      status_type_2: 6,
      status_rate_2: 25,
      status_type_3: 11,
      status_rate_3: 60,
      status_type_4: 0,
      status_rate_4: 0,
      status_type_5: 0,
      status_rate_5: 0,
      chara_id_1: 1061,
      chara_id_2: 1147,
      chara_id_3: 0,
      chara_id_4: 0,
      chara_id_5: 0,
      chara_id_6: 0,
      chara_id_7: 0,
      chara_id_8: 0,
      chara_id_9: 0,
      chara_id_10: 0,
    },
    {
      story_id: 1147002,
      unlock_story_name: "ムイミ（ニューイヤー）のエピソード第2話",
      status_type_1: 2,
      status_rate_1: 10,
      status_type_2: 0,
      status_rate_2: 0,
      status_type_3: 0,
      status_rate_3: 0,
      status_type_4: 0,
      status_rate_4: 0,
      status_type_5: 0,
      status_rate_5: 0,
      chara_id_1: 1147,
      chara_id_2: 1061,
      chara_id_3: 0,
      chara_id_4: 0,
      chara_id_5: 0,
      chara_id_6: 0,
      chara_id_7: 0,
      chara_id_8: 0,
      chara_id_9: 0,
      chara_id_10: 0,
    },
    {
      story_id: 1147003,
      unlock_story_name: "ムイミ（ニューイヤー）のエピソード第3話",
      status_type_1: 2,
      status_rate_1: 30,
      status_type_2: 0,
      status_rate_2: 0,
      status_type_3: 0,
      status_rate_3: 0,
      status_type_4: 0,
      status_rate_4: 0,
      status_type_5: 0,
      status_rate_5: 0,
      chara_id_1: 1147,
      chara_id_2: 1061,
      chara_id_3: 0,
      chara_id_4: 0,
      chara_id_5: 0,
      chara_id_6: 0,
      chara_id_7: 0,
      chara_id_8: 0,
      chara_id_9: 0,
      chara_id_10: 0,
    },
    {
      story_id: 1147004,
      unlock_story_name: "ムイミ（ニューイヤー）のエピソード第4話",
      status_type_1: 2,
      status_rate_1: 50,
      status_type_2: 0,
      status_rate_2: 0,
      status_type_3: 0,
      status_rate_3: 0,
      status_type_4: 0,
      status_rate_4: 0,
      status_type_5: 0,
      status_rate_5: 0,
      chara_id_1: 1147,
      chara_id_2: 1061,
      chara_id_3: 0,
      chara_id_4: 0,
      chara_id_5: 0,
      chara_id_6: 0,
      chara_id_7: 0,
      chara_id_8: 0,
      chara_id_9: 0,
      chara_id_10: 0,
    },
  ],
  unitRarity: [
    {
      unit_id: 106101,
      rarity: 5,
      hp: 639.2,
      hp_growth: 118.4,
      atk: 97.4,
      atk_growth: 18.03,
      magic_str: 0,
      magic_str_growth: 0,
      def: 4.91,
      def_growth: 0.9,
      magic_def: 4.52,
      magic_def_growth: 0.84,
      physical_critical: 20,
      physical_critical_growth: 0,
      magic_critical: 0,
      magic_critical_growth: 0,
      wave_hp_recovery: 0,
      wave_hp_recovery_growth: 0,
      wave_energy_recovery: 0,
      wave_energy_recovery_growth: 0,
      dodge: 0,
      dodge_growth: 0,
      physical_penetrate: 0,
      physical_penetrate_growth: 0,
      magic_penetrate: 0,
      magic_penetrate_growth: 0,
      life_steal: 0,
      life_steal_growth: 0,
      hp_recovery_rate: 0,
      hp_recovery_rate_growth: 0,
      energy_recovery_rate: 0,
      energy_recovery_rate_growth: 0,
      energy_reduce_rate: 0,
      energy_reduce_rate_growth: 0,
      unit_material_id: 31061,
      consume_num: 150,
      consume_gold: 50000,
      accuracy: 0,
      accuracy_growth: 0,
    },
    {
      unit_id: 106101,
      rarity: 4,
      hp: 568.2,
      hp_growth: 98.65,
      atk: 86.58,
      atk_growth: 15.03,
      magic_str: 0,
      magic_str_growth: 0,
      def: 4.37,
      def_growth: 0.75,
      magic_def: 4.02,
      magic_def_growth: 0.7,
      physical_critical: 20,
      physical_critical_growth: 0,
      magic_critical: 0,
      magic_critical_growth: 0,
      wave_hp_recovery: 0,
      wave_hp_recovery_growth: 0,
      wave_energy_recovery: 0,
      wave_energy_recovery_growth: 0,
      dodge: 0,
      dodge_growth: 0,
      physical_penetrate: 0,
      physical_penetrate_growth: 0,
      magic_penetrate: 0,
      magic_penetrate_growth: 0,
      life_steal: 0,
      life_steal_growth: 0,
      hp_recovery_rate: 0,
      hp_recovery_rate_growth: 0,
      energy_recovery_rate: 0,
      energy_recovery_rate_growth: 0,
      energy_reduce_rate: 0,
      energy_reduce_rate_growth: 0,
      unit_material_id: 31061,
      consume_num: 120,
      consume_gold: 40000,
      accuracy: 0,
      accuracy_growth: 0,
    },
    {
      unit_id: 106101,
      rarity: 3,
      hp: 497.1,
      hp_growth: 78.92,
      atk: 75.75,
      atk_growth: 12.02,
      magic_str: 0,
      magic_str_growth: 0,
      def: 3.82,
      def_growth: 0.6,
      magic_def: 3.51,
      magic_def_growth: 0.56,
      physical_critical: 20,
      physical_critical_growth: 0,
      magic_critical: 0,
      magic_critical_growth: 0,
      wave_hp_recovery: 0,
      wave_hp_recovery_growth: 0,
      wave_energy_recovery: 0,
      wave_energy_recovery_growth: 0,
      dodge: 0,
      dodge_growth: 0,
      physical_penetrate: 0,
      physical_penetrate_growth: 0,
      magic_penetrate: 0,
      magic_penetrate_growth: 0,
      life_steal: 0,
      life_steal_growth: 0,
      hp_recovery_rate: 0,
      hp_recovery_rate_growth: 0,
      energy_recovery_rate: 0,
      energy_recovery_rate_growth: 0,
      energy_reduce_rate: 0,
      energy_reduce_rate_growth: 0,
      unit_material_id: 31061,
      consume_num: 100,
      consume_gold: 30000,
      accuracy: 0,
      accuracy_growth: 0,
    },
    {
      unit_id: 106101,
      rarity: 2,
      hp: 426.1,
      hp_growth: 59.19,
      atk: 64.93,
      atk_growth: 9.02,
      magic_str: 0,
      magic_str_growth: 0,
      def: 3.28,
      def_growth: 0.45,
      magic_def: 3.01,
      magic_def_growth: 0.42,
      physical_critical: 20,
      physical_critical_growth: 0,
      magic_critical: 0,
      magic_critical_growth: 0,
      wave_hp_recovery: 0,
      wave_hp_recovery_growth: 0,
      wave_energy_recovery: 0,
      wave_energy_recovery_growth: 0,
      dodge: 0,
      dodge_growth: 0,
      physical_penetrate: 0,
      physical_penetrate_growth: 0,
      magic_penetrate: 0,
      magic_penetrate_growth: 0,
      life_steal: 0,
      life_steal_growth: 0,
      hp_recovery_rate: 0,
      hp_recovery_rate_growth: 0,
      energy_recovery_rate: 0,
      energy_recovery_rate_growth: 0,
      energy_reduce_rate: 0,
      energy_reduce_rate_growth: 0,
      unit_material_id: 31061,
      consume_num: 30,
      consume_gold: 20000,
      accuracy: 0,
      accuracy_growth: 0,
    },
    {
      unit_id: 106101,
      rarity: 1,
      hp: 355.1,
      hp_growth: 39.46,
      atk: 54.11,
      atk_growth: 6.01,
      magic_str: 0,
      magic_str_growth: 0,
      def: 2.73,
      def_growth: 0.3,
      magic_def: 2.51,
      magic_def_growth: 0.28,
      physical_critical: 20,
      physical_critical_growth: 0,
      magic_critical: 0,
      magic_critical_growth: 0,
      wave_hp_recovery: 0,
      wave_hp_recovery_growth: 0,
      wave_energy_recovery: 0,
      wave_energy_recovery_growth: 0,
      dodge: 0,
      dodge_growth: 0,
      physical_penetrate: 0,
      physical_penetrate_growth: 0,
      magic_penetrate: 0,
      magic_penetrate_growth: 0,
      life_steal: 0,
      life_steal_growth: 0,
      hp_recovery_rate: 0,
      hp_recovery_rate_growth: 0,
      energy_recovery_rate: 0,
      energy_recovery_rate_growth: 0,
      energy_reduce_rate: 0,
      energy_reduce_rate_growth: 0,
      unit_material_id: 31061,
      consume_num: 15,
      consume_gold: 10000,
      accuracy: 0,
      accuracy_growth: 0,
    },
  ],
  charaPromotion: [
    { unit_id: 106101, promotion_level: 19, equip_slot_1: 999999, equip_slot_2: 106072, equip_slot_3: 999999, equip_slot_4: 106011, equip_slot_5: 106552, equip_slot_6: 106551 },
    { unit_id: 106101, promotion_level: 18, equip_slot_1: 106072, equip_slot_2: 106071, equip_slot_3: 106341, equip_slot_4: 105017, equip_slot_5: 106551, equip_slot_6: 105557 },
    { unit_id: 106101, promotion_level: 17, equip_slot_1: 106071, equip_slot_2: 105077, equip_slot_3: 105287, equip_slot_4: 105016, equip_slot_5: 105557, equip_slot_6: 105556 },
    { unit_id: 106101, promotion_level: 16, equip_slot_1: 105077, equip_slot_2: 105076, equip_slot_3: 105286, equip_slot_4: 105015, equip_slot_5: 105556, equip_slot_6: 105555 },
    { unit_id: 106101, promotion_level: 15, equip_slot_1: 105076, equip_slot_2: 105075, equip_slot_3: 105285, equip_slot_4: 105014, equip_slot_5: 105555, equip_slot_6: 105554 },
    { unit_id: 106101, promotion_level: 14, equip_slot_1: 105075, equip_slot_2: 105074, equip_slot_3: 105284, equip_slot_4: 105013, equip_slot_5: 105554, equip_slot_6: 105553 },
    { unit_id: 106101, promotion_level: 13, equip_slot_1: 105074, equip_slot_2: 105073, equip_slot_3: 105343, equip_slot_4: 105012, equip_slot_5: 105553, equip_slot_6: 105552 },
    { unit_id: 106101, promotion_level: 12, equip_slot_1: 105073, equip_slot_2: 105072, equip_slot_3: 105282, equip_slot_4: 105011, equip_slot_5: 105552, equip_slot_6: 105551 },
    { unit_id: 106101, promotion_level: 11, equip_slot_1: 105072, equip_slot_2: 105071, equip_slot_3: 105341, equip_slot_4: 104014, equip_slot_5: 105551, equip_slot_6: 104554 },
    { unit_id: 106101, promotion_level: 10, equip_slot_1: 105071, equip_slot_2: 104074, equip_slot_3: 104284, equip_slot_4: 104013, equip_slot_5: 104554, equip_slot_6: 104552 },
    { unit_id: 106101, promotion_level: 9, equip_slot_1: 104074, equip_slot_2: 104013, equip_slot_3: 104402, equip_slot_4: 104012, equip_slot_5: 104552, equip_slot_6: 104551 },
    { unit_id: 106101, promotion_level: 8, equip_slot_1: 104073, equip_slot_2: 104072, equip_slot_3: 104282, equip_slot_4: 104011, equip_slot_5: 104551, equip_slot_6: 103553 },
    { unit_id: 106101, promotion_level: 7, equip_slot_1: 104072, equip_slot_2: 104071, equip_slot_3: 104281, equip_slot_4: 103553, equip_slot_5: 103583, equip_slot_6: 103552 },
    { unit_id: 106101, promotion_level: 6, equip_slot_1: 104071, equip_slot_2: 103072, equip_slot_3: 103283, equip_slot_4: 103401, equip_slot_5: 103582, equip_slot_6: 103552 },
    { unit_id: 106101, promotion_level: 5, equip_slot_1: 103072, equip_slot_2: 103012, equip_slot_3: 103282, equip_slot_4: 103401, equip_slot_5: 103581, equip_slot_6: 103551 },
    { unit_id: 106101, promotion_level: 4, equip_slot_1: 103012, equip_slot_2: 103071, equip_slot_3: 103281, equip_slot_4: 103431, equip_slot_5: 102582, equip_slot_6: 102552 },
    { unit_id: 106101, promotion_level: 3, equip_slot_1: 103071, equip_slot_2: 102013, equip_slot_3: 102282, equip_slot_4: 102401, equip_slot_5: 102581, equip_slot_6: 102551 },
    { unit_id: 106101, promotion_level: 2, equip_slot_1: 102013, equip_slot_2: 102071, equip_slot_3: 102281, equip_slot_4: 102493, equip_slot_5: 101581, equip_slot_6: 101551 },
    { unit_id: 106101, promotion_level: 1, equip_slot_1: 101071, equip_slot_2: 101071, equip_slot_3: 101281, equip_slot_4: 101401, equip_slot_5: 101581, equip_slot_6: 101551 },
  ],
  charaPromotionStatus: [
    {
      unit_id: 106101,
      promotion_level: 19,
      hp: 6965,
      atk: 7620,
      magic_str: 0,
      def: 120,
      magic_def: 76,
      physical_critical: 950,
      magic_critical: 0,
      wave_hp_recovery: 2405,
      wave_energy_recovery: 222,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 24,
      energy_reduce_rate: 0,
      accuracy: 80,
    },
    {
      unit_id: 106101,
      promotion_level: 18,
      hp: 6560,
      atk: 6709,
      magic_str: 0,
      def: 116,
      magic_def: 72,
      physical_critical: 789,
      magic_critical: 0,
      wave_hp_recovery: 2405,
      wave_energy_recovery: 222,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 24,
      energy_reduce_rate: 0,
      accuracy: 80,
    },
    {
      unit_id: 106101,
      promotion_level: 17,
      hp: 6430,
      atk: 5898,
      magic_str: 0,
      def: 113,
      magic_def: 67,
      physical_critical: 616,
      magic_critical: 0,
      wave_hp_recovery: 2405,
      wave_energy_recovery: 222,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 24,
      energy_reduce_rate: 0,
      accuracy: 76,
    },
    {
      unit_id: 106101,
      promotion_level: 16,
      hp: 6320,
      atk: 5155,
      magic_str: 0,
      def: 107,
      magic_def: 63,
      physical_critical: 504,
      magic_critical: 0,
      wave_hp_recovery: 2405,
      wave_energy_recovery: 222,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 24,
      energy_reduce_rate: 0,
      accuracy: 69,
    },
    {
      unit_id: 106101,
      promotion_level: 15,
      hp: 6160,
      atk: 4444,
      magic_str: 0,
      def: 99,
      magic_def: 61,
      physical_critical: 400,
      magic_critical: 0,
      wave_hp_recovery: 2405,
      wave_energy_recovery: 222,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 24,
      energy_reduce_rate: 0,
      accuracy: 66,
    },
    {
      unit_id: 106101,
      promotion_level: 14,
      hp: 5910,
      atk: 3800,
      magic_str: 0,
      def: 93,
      magic_def: 55,
      physical_critical: 308,
      magic_critical: 0,
      wave_hp_recovery: 2405,
      wave_energy_recovery: 196,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 24,
      energy_reduce_rate: 0,
      accuracy: 66,
    },
    {
      unit_id: 106101,
      promotion_level: 13,
      hp: 5620,
      atk: 3190,
      magic_str: 0,
      def: 88,
      magic_def: 51,
      physical_critical: 225,
      magic_critical: 0,
      wave_hp_recovery: 2285,
      wave_energy_recovery: 165,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 24,
      energy_reduce_rate: 0,
      accuracy: 63,
    },
    {
      unit_id: 106101,
      promotion_level: 12,
      hp: 5250,
      atk: 2660,
      magic_str: 0,
      def: 82,
      magic_def: 45,
      physical_critical: 156,
      magic_critical: 0,
      wave_hp_recovery: 2165,
      wave_energy_recovery: 140,
      dodge: 7,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 11,
      hp_recovery_rate: 25,
      energy_recovery_rate: 22,
      energy_reduce_rate: 0,
      accuracy: 50,
    },
    {
      unit_id: 106101,
      promotion_level: 11,
      hp: 4780,
      atk: 2198,
      magic_str: 0,
      def: 78,
      magic_def: 43,
      physical_critical: 98,
      magic_critical: 0,
      wave_hp_recovery: 2015,
      wave_energy_recovery: 140,
      dodge: 5,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 9,
      hp_recovery_rate: 25,
      energy_recovery_rate: 20,
      energy_reduce_rate: 0,
      accuracy: 20,
    },
    {
      unit_id: 106101,
      promotion_level: 10,
      hp: 4400,
      atk: 1761,
      magic_str: 0,
      def: 74,
      magic_def: 38,
      physical_critical: 40,
      magic_critical: 0,
      wave_hp_recovery: 1715,
      wave_energy_recovery: 140,
      dodge: 3,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 9,
      hp_recovery_rate: 15,
      energy_recovery_rate: 15,
      energy_reduce_rate: 0,
      accuracy: 5,
    },
    {
      unit_id: 106101,
      promotion_level: 9,
      hp: 4230,
      atk: 1326,
      magic_str: 0,
      def: 68,
      magic_def: 32,
      physical_critical: 10,
      magic_critical: 0,
      wave_hp_recovery: 1565,
      wave_energy_recovery: 125,
      dodge: 3,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 6,
      hp_recovery_rate: 5,
      energy_recovery_rate: 5,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
    {
      unit_id: 106101,
      promotion_level: 8,
      hp: 3695,
      atk: 953,
      magic_str: 0,
      def: 59,
      magic_def: 25,
      physical_critical: 0,
      magic_critical: 0,
      wave_hp_recovery: 1115,
      wave_energy_recovery: 100,
      dodge: 3,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 6,
      hp_recovery_rate: 5,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
    {
      unit_id: 106101,
      promotion_level: 7,
      hp: 2855,
      atk: 687,
      magic_str: 0,
      def: 46,
      magic_def: 18,
      physical_critical: 0,
      magic_critical: 0,
      wave_hp_recovery: 580,
      wave_energy_recovery: 75,
      dodge: 3,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 6,
      hp_recovery_rate: 5,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
    {
      unit_id: 106101,
      promotion_level: 6,
      hp: 2185,
      atk: 458,
      magic_str: 0,
      def: 31,
      magic_def: 12,
      physical_critical: 0,
      magic_critical: 0,
      wave_hp_recovery: 345,
      wave_energy_recovery: 50,
      dodge: 3,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 3,
      hp_recovery_rate: 5,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
    {
      unit_id: 106101,
      promotion_level: 5,
      hp: 1275,
      atk: 288,
      magic_str: 0,
      def: 17,
      magic_def: 7,
      physical_critical: 0,
      magic_critical: 0,
      wave_hp_recovery: 255,
      wave_energy_recovery: 50,
      dodge: 3,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 5,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
    {
      unit_id: 106101,
      promotion_level: 4,
      hp: 705,
      atk: 159,
      magic_str: 0,
      def: 11,
      magic_def: 3,
      physical_critical: 0,
      magic_critical: 0,
      wave_hp_recovery: 255,
      wave_energy_recovery: 25,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
    {
      unit_id: 106101,
      promotion_level: 3,
      hp: 305,
      atk: 67,
      magic_str: 0,
      def: 6,
      magic_def: 1,
      physical_critical: 0,
      magic_critical: 0,
      wave_hp_recovery: 200,
      wave_energy_recovery: 5,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
    {
      unit_id: 106101,
      promotion_level: 2,
      hp: 65,
      atk: 19,
      magic_str: 0,
      def: 3,
      magic_def: 0,
      physical_critical: 0,
      magic_critical: 0,
      wave_hp_recovery: 125,
      wave_energy_recovery: 0,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
  ],
  equipments: [
    {
      equipment_id: 106011,
      equipment_name: "輝光剣アダマス",
      description: "原初の金剛石を削り鍛えられたと伝\\n説に伝わる宝石剣。幾星霜の時を経\\nても変わらぬ光を放ち続け、永世折\\nれずにその輝きで魔を祓う。",
      promotion_level: 6,
      craft_flg: 1,
      equipment_enhance_point: 680,
      sale_price: 34000,
      require_level: 112,
      hp: 155,
      atk: 191,
      magic_str: 0,
      def: 0,
      magic_def: 0,
      physical_critical: 21,
      magic_critical: 0,
      wave_hp_recovery: 0,
      wave_energy_recovery: 0,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      enable_donation: 0,
      accuracy: 0,
      display_item: 0,
      item_type: 0,
      max_equipment_enhance_level: 5,
    },
    {
      equipment_id: 106072,
      equipment_name: "チョコバナナダガー",
      description: "チョコバナナでできたお菓子の国秘\\n伝の短刀。固まったチョコの表面の\\n堅牢さとバナナの粘る刀身が無限の\\n切れ味を生み出す。",
      promotion_level: 6,
      craft_flg: 1,
      equipment_enhance_point: 880,
      sale_price: 34000,
      require_level: 118,
      hp: 250,
      atk: 199,
      magic_str: 0,
      def: 0,
      magic_def: 0,
      physical_critical: 15,
      magic_critical: 0,
      wave_hp_recovery: 0,
      wave_energy_recovery: 0,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      enable_donation: 0,
      accuracy: 0,
      display_item: 0,
      item_type: 0,
      max_equipment_enhance_level: 5,
    },
    {
      equipment_id: 106551,
      equipment_name: "神紅輪ルビーローズ",
      description: "情熱を司るルビーの薔薇が施された\\n指輪。戦神の力を宿しており、万の\\n軍勢を薙ぎ払う絶対的な力と、邪神\\nの恐怖すら振り払う勇気を授ける。",
      promotion_level: 6,
      craft_flg: 1,
      equipment_enhance_point: 600,
      sale_price: 34000,
      require_level: 114,
      hp: 95,
      atk: 124,
      magic_str: 0,
      def: 0,
      magic_def: 0,
      physical_critical: 40,
      magic_critical: 0,
      wave_hp_recovery: 0,
      wave_energy_recovery: 0,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      enable_donation: 0,
      accuracy: 0,
      display_item: 0,
      item_type: 0,
      max_equipment_enhance_level: 5,
    },
    {
      equipment_id: 106552,
      equipment_name: "ポップコーンネックレス",
      description: "お菓子の国王家に伝わる宝石の如く\\n輝きを放つポップコーンの首飾り。\\n一粒一粒から放たれる香りが装着者\\nの食欲と闘争本能に火をつける。",
      promotion_level: 6,
      craft_flg: 1,
      equipment_enhance_point: 600,
      sale_price: 34000,
      require_level: 120,
      hp: 100,
      atk: 137,
      magic_str: 0,
      def: 0,
      magic_def: 0,
      physical_critical: 41,
      magic_critical: 0,
      wave_hp_recovery: 0,
      wave_energy_recovery: 0,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0,
      energy_reduce_rate: 0,
      enable_donation: 0,
      accuracy: 0,
      display_item: 0,
      item_type: 0,
      max_equipment_enhance_level: 5,
    },
  ],
  uniqueEquipment: [
    {
      equipment_id: 130611,
      equipment_name: "絆の証",
      description: "ムイミが肌身離さず着用しているブ\\nローチ。かつてこれを託してくれた\\n相棒との絆の温もりが、天楼覇断剣\\nを振るう力を与える。",
      promotion_level: 98,
      craft_flg: 1,
      equipment_enhance_point: 0,
      sale_price: 0,
      require_level: 1,
      hp: 0,
      atk: 99,
      magic_str: 0,
      def: 0,
      magic_def: 0,
      physical_critical: 9,
      magic_critical: 0,
      wave_hp_recovery: 0,
      wave_energy_recovery: 0,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 1,
      energy_reduce_rate: 0,
      enable_donation: 0,
      accuracy: 0,
      item_id_1: 31061,
      consume_num_1: 50,
      item_id_2: 140000,
      consume_num_2: 3,
      item_id_3: 0,
      consume_num_3: 0,
      item_id_4: 0,
      consume_num_4: 0,
      item_id_5: 0,
      consume_num_5: 0,
      item_id_6: 0,
      consume_num_6: 0,
      item_id_7: 0,
      consume_num_7: 0,
      item_id_8: 0,
      consume_num_8: 0,
      item_id_9: 0,
      consume_num_9: 0,
      item_id_10: 0,
      consume_num_10: 0,
    },
  ],
  uniqueEquipmentEnhance: [
    {
      equipment_id: 130611,
      equipment_name: "絆の証",
      description: "ムイミが肌身離さず着用しているブ\\nローチ。かつてこれを託してくれた\\n相棒との絆の温もりが、天楼覇断剣\\nを振るう力を与える。",
      promotion_level: 98,
      hp: 0,
      atk: 4.95,
      magic_str: 0,
      def: 0,
      magic_def: 0,
      physical_critical: 0.45,
      magic_critical: 0,
      wave_hp_recovery: 0,
      wave_energy_recovery: 0,
      dodge: 0,
      physical_penetrate: 0,
      magic_penetrate: 0,
      life_steal: 0,
      hp_recovery_rate: 0,
      energy_recovery_rate: 0.05,
      energy_reduce_rate: 0,
      accuracy: 0,
    },
  ],
  unitSkillData: [
    {
      unit_id: 106101,
      union_burst: 1061001,
      main_skill_1: 1061002,
      main_skill_2: 1061003,
      main_skill_3: 0,
      main_skill_4: 0,
      main_skill_5: 0,
      main_skill_6: 0,
      main_skill_7: 0,
      main_skill_8: 0,
      main_skill_9: 0,
      main_skill_10: 0,
      ex_skill_1: 1061501,
      ex_skill_evolution_1: 1061511,
      ex_skill_2: 0,
      ex_skill_evolution_2: 0,
      ex_skill_3: 0,
      ex_skill_evolution_3: 0,
      ex_skill_4: 0,
      ex_skill_evolution_4: 0,
      ex_skill_5: 0,
      ex_skill_evolution_5: 0,
      sp_skill_1: 1061101,
      sp_skill_2: 1061102,
      sp_skill_3: 0,
      sp_skill_4: 0,
      sp_skill_5: 0,
      union_burst_evolution: 0,
      main_skill_evolution_1: 1061012,
      main_skill_evolution_2: 0,
      sp_skill_evolution_1: 1061111,
      sp_skill_evolution_2: 0,
    },
  ],
  skillData: [
    {
      skill_id: 1061001,
      name: "天楼覇断剣",
      skill_type: 0,
      skill_area_width: 0,
      skill_cast_time: 0,
      action_1: 106100101,
      action_2: 106100102,
      action_3: 106100103,
      action_4: 0,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 0,
      depend_action_4: 0,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "目の前の敵１キャラに物理特大ダメージを与える。さらにＴＰが無くなるまでの間天楼覇断剣を装備する。",
      icon_type: 1001,
    },
    {
      skill_id: 1061002,
      name: "ビビらせてやる！",
      skill_type: 0,
      skill_area_width: 0,
      skill_cast_time: 0.34,
      action_1: 106100201,
      action_2: 106100202,
      action_3: 106100203,
      action_4: 106100204,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 106100201,
      depend_action_4: 106100202,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "前方範囲内の敵すべてに物理小ダメージを与え、さらにスタンさせて小さく吹き飛ばす。",
      icon_type: 2018,
    },
    {
      skill_id: 1061003,
      name: "こっちだこっち！",
      skill_type: 1,
      skill_area_width: 0,
      skill_cast_time: 0.34,
      action_1: 106100301,
      action_2: 0,
      action_3: 0,
      action_4: 0,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 0,
      depend_action_4: 0,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "前方範囲内の敵すべての物理防御力を小ダウンさせる。",
      icon_type: 2004,
    },
    {
      skill_id: 1061012,
      name: "ビビらせてやる！+",
      skill_type: 0,
      skill_area_width: 0,
      skill_cast_time: 0.34,
      action_1: 106101201,
      action_2: 106101202,
      action_3: 106101203,
      action_4: 106101204,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 106101201,
      depend_action_4: 106101202,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "前方範囲内の敵すべてに物理中ダメージを与え、さらにスタンさせて小さく吹き飛ばす。",
      icon_type: 2018,
    },
    {
      skill_id: 1061101,
      name: "天楼廻刃斬",
      skill_type: 1,
      skill_area_width: 0,
      skill_cast_time: 0.25,
      action_1: 106110101,
      action_2: 0,
      action_3: 0,
      action_4: 0,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 0,
      depend_action_4: 0,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "目の前の敵１キャラに物理特大ダメージを与える。",
      icon_type: 1002,
    },
    {
      skill_id: 1061102,
      name: "天楼閃薙斬",
      skill_type: 1,
      skill_area_width: 0,
      skill_cast_time: 0.25,
      action_1: 106110201,
      action_2: 0,
      action_3: 0,
      action_4: 0,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 0,
      depend_action_4: 0,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "前方範囲内の敵すべてに物理大ダメージを与える。",
      icon_type: 1002,
    },
    {
      skill_id: 1061111,
      name: "天楼廻刃斬＋",
      skill_type: 1,
      skill_area_width: 0,
      skill_cast_time: 0.25,
      action_1: 106111101,
      action_2: 0,
      action_3: 0,
      action_4: 0,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 0,
      depend_action_4: 0,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "目の前の敵１キャラに物理特大ダメージを与える。",
      icon_type: 1002,
    },
    {
      skill_id: 1061501,
      name: "ポテンシャルフォース",
      skill_type: 0,
      skill_area_width: 0,
      skill_cast_time: 0,
      action_1: 106150101,
      action_2: 0,
      action_3: 0,
      action_4: 0,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 0,
      depend_action_4: 0,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "バトル開始時に自分の物理攻撃力を中アップさせる。",
      icon_type: 3001,
    },
    {
      skill_id: 1061511,
      name: "ポテンシャルフォース+",
      skill_type: 0,
      skill_area_width: 0,
      skill_cast_time: 0,
      action_1: 106151101,
      action_2: 0,
      action_3: 0,
      action_4: 0,
      action_5: 0,
      action_6: 0,
      action_7: 0,
      depend_action_1: 0,
      depend_action_2: 0,
      depend_action_3: 0,
      depend_action_4: 0,
      depend_action_5: 0,
      depend_action_6: 0,
      depend_action_7: 0,
      description: "バトル開始時に自分の物理攻撃力を大アップさせる。",
      icon_type: 3001,
    },
  ],
  skillAction: [
    {
      action_id: 106100101,
      class_id: 1,
      action_type: 14,
      action_detail_1: 2,
      action_detail_2: 10610102,
      action_detail_3: 0,
      action_value_1: 100,
      action_value_2: 0,
      action_value_3: 0,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 2,
      target_area: 1,
      target_range: 0,
      target_type: 7,
      target_number: 0,
      target_count: 1,
      description: "",
      level_up_disp: "",
    },
    {
      action_id: 106100102,
      class_id: 1,
      action_type: 14,
      action_detail_1: 3,
      action_detail_2: 10610101,
      action_detail_3: 0,
      action_value_1: 0,
      action_value_2: 0,
      action_value_3: 0,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 2,
      target_area: 1,
      target_range: 0,
      target_type: 7,
      target_number: 0,
      target_count: 1,
      description: "",
      level_up_disp: "",
    },
    {
      action_id: 106100103,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 50,
      action_value_2: 50,
      action_value_3: 4.2,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: -1,
      target_type: 3,
      target_number: 0,
      target_count: 1,
      description: "敵単体に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106100201,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 3.4,
      action_value_2: 3.4,
      action_value_3: 0.27,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 280,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "斬撃で範囲内の敵に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106100202,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 4.5,
      action_value_2: 4.5,
      action_value_3: 0.36,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 280,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "蹴りで範囲内の敵に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106100203,
      class_id: 1,
      action_type: 8,
      action_detail_1: 7,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 0,
      action_value_2: 0,
      action_value_3: 1.5,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 280,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "範囲内の敵を一定時間行動不能にする",
      level_up_disp: "スタンの確定成功Ｌｖ+1",
    },
    {
      action_id: 106100204,
      class_id: 1,
      action_type: 3,
      action_detail_1: 3,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 150,
      action_value_2: 0,
      action_value_3: 300,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 280,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "",
      level_up_disp: "",
    },
    {
      action_id: 106100301,
      class_id: 1,
      action_type: 10,
      action_detail_1: 21,
      action_detail_2: 1,
      action_detail_3: 0,
      action_value_1: 1,
      action_value_2: 0.375,
      action_value_3: 0.375,
      action_value_4: 12,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 1,
      target_assignment: 1,
      target_area: 1,
      target_range: 280,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "範囲内の敵の物理防御力を{0}ダウン",
      level_up_disp: "物理防御力ダウン+{0}",
    },
    {
      action_id: 106101201,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 5.1,
      action_value_2: 5.1,
      action_value_3: 0.405,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 300,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "斬撃で範囲内の敵に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106101202,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 6.75,
      action_value_2: 6.75,
      action_value_3: 0.54,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 300,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "蹴りで範囲内の敵に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106101203,
      class_id: 1,
      action_type: 8,
      action_detail_1: 7,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 0,
      action_value_2: 0,
      action_value_3: 1.5,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 300,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "範囲内の敵を一定時間行動不能にする",
      level_up_disp: "スタンの確定成功Ｌｖ+1",
    },
    {
      action_id: 106101204,
      class_id: 1,
      action_type: 3,
      action_detail_1: 3,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 200,
      action_value_2: 0,
      action_value_3: 400,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: 300,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "",
      level_up_disp: "",
    },
    {
      action_id: 106110101,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 60,
      action_value_2: 60,
      action_value_3: 4.8,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: -1,
      target_type: 3,
      target_number: 0,
      target_count: 1,
      description: "敵単体に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106110201,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 40,
      action_value_2: 40,
      action_value_3: 3.6,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 2,
      target_range: 575,
      target_type: 3,
      target_number: 0,
      target_count: 99,
      description: "敵単体に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106111101,
      class_id: 1,
      action_type: 1,
      action_detail_1: 1,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 120,
      action_value_2: 120,
      action_value_3: 9.6,
      action_value_4: 0,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 1,
      target_area: 1,
      target_range: -1,
      target_type: 3,
      target_number: 0,
      target_count: 1,
      description: "敵単体に{0}の物理ダメージ",
      level_up_disp: "物理ダメージ+{0}",
    },
    {
      action_id: 106150101,
      class_id: 1,
      action_type: 90,
      action_detail_1: 2,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 1,
      action_value_2: 15,
      action_value_3: 15,
      action_value_4: 1,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 0,
      target_area: 0,
      target_range: 0,
      target_type: 0,
      target_number: 0,
      target_count: 0,
      description: "自分の物理攻撃力を{0}アップ",
      level_up_disp: "物理攻撃力アップ+{0}",
    },
    {
      action_id: 106151101,
      class_id: 1,
      action_type: 90,
      action_detail_1: 2,
      action_detail_2: 0,
      action_detail_3: 0,
      action_value_1: 1,
      action_value_2: 240,
      action_value_3: 15,
      action_value_4: 1,
      action_value_5: 0,
      action_value_6: 0,
      action_value_7: 0,
      target_assignment: 0,
      target_area: 0,
      target_range: 0,
      target_type: 0,
      target_number: 0,
      target_count: 0,
      description: "自分の物理攻撃力を{0}アップ",
      level_up_disp: "物理攻撃力アップ+{0}",
    },
  ],
  unitAttackPattern: [
    {
      pattern_id: 10610101,
      unit_id: 106101,
      loop_start: 3,
      loop_end: 9,
      atk_pattern_1: 1002,
      atk_pattern_2: 1001,
      atk_pattern_3: 1,
      atk_pattern_4: 1002,
      atk_pattern_5: 1,
      atk_pattern_6: 1001,
      atk_pattern_7: 1,
      atk_pattern_8: 1002,
      atk_pattern_9: 1001,
      atk_pattern_10: 0,
      atk_pattern_11: 0,
      atk_pattern_12: 0,
      atk_pattern_13: 0,
      atk_pattern_14: 0,
      atk_pattern_15: 0,
      atk_pattern_16: 0,
      atk_pattern_17: 0,
      atk_pattern_18: 0,
      atk_pattern_19: 0,
      atk_pattern_20: 0,
    },
    {
      pattern_id: 10610102,
      unit_id: 106101,
      loop_start: 2,
      loop_end: 3,
      atk_pattern_1: 2001,
      atk_pattern_2: 2002,
      atk_pattern_3: 2001,
      atk_pattern_4: 0,
      atk_pattern_5: 0,
      atk_pattern_6: 0,
      atk_pattern_7: 0,
      atk_pattern_8: 0,
      atk_pattern_9: 0,
      atk_pattern_10: 0,
      atk_pattern_11: 0,
      atk_pattern_12: 0,
      atk_pattern_13: 0,
      atk_pattern_14: 0,
      atk_pattern_15: 0,
      atk_pattern_16: 0,
      atk_pattern_17: 0,
      atk_pattern_18: 0,
      atk_pattern_19: 0,
      atk_pattern_20: 0,
    },
  ],
};

// 角色剧情属性        + 四舍五入(2 * 所有装备属性     + 角色Rank汇总数据       + 角色星级数据 + 角色星级成长数据 * 等级)          + 向上取整(专武数据                + 专武升级数据 * 专武等级)
// chara_story_status + Math.round(2 * equipment_data  + unit_promotion_status + unitRarity  + unitRarity.*_growth * level) + Math.ceil(unique_equipment_data + unique_equipment_enhance_rate * level)

let atk = 0;

data.charaStoryStatus.forEach((element) => {
  for (let i = 1; i <= 5; i++) {
    if (element["status_type_" + i] === 2) {
      atk += element["status_rate_" + i];
    }
  }
});

let sum = 0;
data.equipments.forEach((element) => {
  sum += 2 * element.atk;
});

sum += data.charaPromotionStatus[0].atk;
sum += data.unitRarity[0].atk;
sum += data.unitRarity[0].atk_growth * (184 + 19);
atk = Math.round(atk + sum);

atk += Math.ceil(data.uniqueEquipment[0].atk + data.uniqueEquipmentEnhance[0].atk * 179);

console.log(atk);
